### ISSUE TITLE
Call of overloaded "<method>" is ambiguous

### ISSUE THREAD

**Issue by dzalf** [PatrickBaus/Arduino-TMP1075#1]
Dear Patrick

I plan to use your library to read a group of devices mounted on a custom PCB. 
I am facing some issues with the current implementation. it seems like the I2C address should be passed explicitly to the private value.

![image](https://user-images.githubusercontent.com/3759916/196305166-14c3a92b-2a9b-4dde-b9e9-388182aebf43.png)

I wonder if you were able to test this on Arduino platforms (such as the Mega 2560, for instance)

![image](https://user-images.githubusercontent.com/3759916/196305396-9d125811-d6d8-41c2-b699-c9d3f16513fc.png)

I will fork your repo and play around with the constructors, perhaps that will make the compiler _happier_

**Comment by PatrickBaus** [comment]
Hello Daniel,

thanks for your report. Indeed, this is a bug. I wrongfully used a uint16_t for the i2cAdress. It should be a uin8_t.

**Comment by dzalf** [comment]
Indeed! 

I noticed this when I was reading the library again on the bus 😄 

Let me have a look to see if I face any other issues.

Thanks for the prompt response and quick help

Cheers
