### ISSUE TITLE
Missing .properties file when using Arduino IDE

### ISSUE THREAD

**Issue by AngryPotato30** [PatrickBaus/Arduino-TMP1075#3]
Hi Patrick,

Thank you very much for creating this library. I am yet to try it with an actual device.
One thing I have noticed is that the repo is missing the library.properties file which is apparently a key file to have when using the Arduino IDE. Without this file the IDE does not recognize it as a library and therefore fails the installing process. This might be obvious for an experienced coder but I am a novice myself and it took me a while to get to the bottom of it.

Again, thank you for the library and hopefully one day I get to a point when I can write my own libraries to share.

Kind regards.

David

**Comment by PatrickBaus** [comment]
Hello David,

thanks for the feedback. Indeed, I did not yet convert the lib to the new Arduino standard. I shall try to find some time on the weekend to wrap this up.

**Comment by PatrickBaus** [comment]
I finally found some time to fix this. Thanks for reporting. I hope it works for you now.
